library(shiny)
library(maptools)
library(leaflet)
library(RColorBrewer)
library(ggplot2)
library(raster)
library(Cairo)
library(gridExtra)
library(chron)
library(zoo)
library(fields)
setwd("C:\\GoogleDrive\\Interactive\\Rcode\\Shiny\\ClimateApp")
runApp("ClimateShiny")

